### ISSUE TITLE
Add a Markdown Table of Contents to All Article Pages

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality-docs#16]
The GitHub pages flavor of markdown allows to add a marker to pages in order to insert an automatically generated table of contents at that point. This is currently done on the [Getting Started page](https://github.com/AdamsLair/duality-docs/blob/989f639a96ce4f4f932228a38b81f6e6245efb91/pages/v2/getting-started.md). 

To provide a better overview on page contents, add this marker to all pages that have more than one part, so that it's between the page summary and the first headline.

```
This is the page summary.

* TOC
{:toc}

# The First Headline

More text.
...
```

So that when compiled, it will look like this:
![chrome_2018-03-04_16-42-59](https://user-images.githubusercontent.com/14859411/36947385-25e349ba-1fcb-11e8-8476-d9ca573c948e.png)

**Comment by BobGneu** [comment]
Does it do this for all levels or just h1 through h3?

**Comment by ilexp** [comment]
Haven't checked, but I think all headings are used. From what I've [read](http://www.seanbuscay.com/blog/jekyll-toc-markdown/), this is a Kramdown feature, which has a [docs page here](https://kramdown.gettalong.org/converter/html.html#toc). It doesn't seem to state explicitly that all headers are used, but I would assume that it should state if they were not.

_Edit:_ Re-read their docs page. Here it is:
> When the auto_ids option is set, all headers will appear in the table of contents as they all will have an ID.

**Comment by KulkoBSW** [comment]
How could I check easily if this works, after adding the markdowns?

I would be willing to contribute the change, but I Think first step woiuld be to create a branch? Which seems to need additional privileges. 

PS: This is my first try at contributing at a larger project spo sorry ofr the stupid questions.

**Comment by ilexp** [comment]
Hey there! No worries, we'll get you started.

> I would be willing to contribute the change, but I Think first step woiuld be to create a branch? Which seems to need additional privileges.

You can't create branches on this repository itself unless you're a member of the docs team, but you don't actually need to do that for contributing: [Fork the docs repository](https://github.com/AdamsLair/duality-docs#fork-destination-box) first, so you'll get your own copy of the entire thing and check out your forked repository locally. You can then create branches with full access and push them back to your fork.

When you're done and ready for review / merge, you can create a Pull Request on the main repository, where you request that we pull changes from your feature branch into our master branch. We'll review and work together until it's ready for merge.

> How could I check easily if this works, after adding the markdowns?

For this, you'll need a local Jekyll setup that mirros how GitHub generates the pages. You'll find more info on this [here](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/).

**Comment by ilexp** [comment]
Done by @KulkoBSW. Closing this.
