### ISSUE TITLE
Investigate Adding an Auto-Generated Table of Contents to the Sidebar

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality-docs#17]
### Summary

Adding table of contents via markdown as part of the content is a great first step, but for longer articles, it becomes tedious to scroll all the way up in order to see it. Investigate whether it is possible to add an auto-generated table of contents to the sidebar.

### Analysis

- Generating the table of contents should happen at build time, not in the browser via JS.
- [This Jekyll template](https://github.com/allejo/jekyll-toc) looks like it can do exactly this. Adding it to the includes folder and using it in the sidebar should be easy enough.
- The stylesheet might need to be extended in order to style the result, so that it matches existing sidebar contents.
- The TOC should be below the page version list, which should be styled to have a bottom border and margin as well as the existing top border and margin.
- The TOC should not be displayed on pages that have only one headline or less. This might require looking into the Jekyll template code an potentially adjusting it.
- When scrolling downwards to the point that the TOCs upper border would be above the window top, it should assume a fixed window position, so it always remains visible. This will likely require JS code, but it should preferable only toggle between different CSS classes, rather than continuously update TOC positions.

**Comment by ilexp** [comment]
> When scrolling downwards to the point that the TOCs upper border would be above the window top, it should assume a fixed window position, so it always remains visible. **This will likely require JS code**, but it should preferable only toggle between different CSS classes, rather than continuously update TOC positions.

Actually, it won't. Use [`position: sticky`](https://gedd.ski/post/position-sticky/) instead. [Browser support is > 85% and growing](https://caniuse.com/#feat=css-sticky), which already includes all major desktop browsers, and mobile won't have a sidebar anyway.

**Comment by KulkoBSW** [comment]
The Script works and the Sticky bit is also fine on Firefox and chrome but not IE11.

But I dont think this looks really good. 

First its really far down, which is going to get even worse once the site content becomes larger still 
On the other hand the TOC does not stick out but loooks like the next part of the site content table. So I think it will just be ignored. 

I attached a Screenshot. (Please ignore the smaller font, I just wanted to check in with you first)
![duality sidebartoc](https://user-images.githubusercontent.com/37846322/38330007-bc87ea1e-384f-11e8-9a03-4ab939fd3daf.png)

**Comment by ilexp** [comment]
Looks good so far 👍 

> First its really far down, which is going to get even worse once the site content becomes larger still
On the other hand the TOC does not stick out but loooks like the next part of the site content table. So I think it will just be ignored.

That's a good point, but from my side, I'd say it's not _necessarily_ a problem - for the first overview, we have the inline TOC in the article itself after all. The sidebar TOC is primarily for navigating quickly while being scrolled way down. What's good is that it's on the top and accessible without scrolling as soon as the inline TOC is not within a reasonable margin.

Alternatively, we could replace the top-level navigation with the article TOC for any article that is a proper "leaf" page. Could be done very similar to [how pages display their child pages](https://adamslair.github.io/duality-docs/pages/v2/Guidelines.html) when [any are](https://github.com/AdamsLair/duality-docs/blob/d51af70bbd86817dde7408f2f9bf531a7ee8dd64/pages/v2/Guidelines/Best-Practices.md) [defined](https://github.com/AdamsLair/duality-docs/blob/d51af70bbd86817dde7408f2f9bf531a7ee8dd64/pages/v2/Guidelines/Common-Pitfalls.md).

Thoughts?

**Comment by ilexp** [comment]
## Progress

- Implemented the above linked auto-generated table of contents in the sidebar.
- Changed sidebar logic, so the auto-generated TOC will replace the site overview where appropriate, instead of being added at the bottom.
- Sidebar contents are now sticky.
- Tweaked the stylesheet to make sidebar TOCs look a little nicer, and responsive behavior allow a sidebar on tablet resolutions.

Closing this.
