### ISSUE TITLE
Add a article about coroutines

### ISSUE THREAD

**Issue by Rick-van-Dam** [AdamsLair/duality-docs#38]

**Comment by ilexp** [comment]
Removed the `Docs` tag - that one is only for issues that will change stuff in the docs project itself, like infrastructure, overall layout, issue handling, etc. It's not meant for (regular / non-refactoring) content changes, or we'd have to flag pretty much every issue in this repo with it 😁 Should probably clarify this somewhere, the terminology is a bit confusing.

_Edit:_ Renamed the tag to `Infrastructure` for now, updated description
